### PR TITLE
feat: Possibility to use .env files

### PR DESCRIPTION
**Pull request by cv65kr**
# Reason for This PR

closes: https://github.com/roadrunner-server/roadrunner/issues/1077

## Description of Changes

- Possibility to use .env files in RR, OS environment variables has always highest priority. 
- Under experimental flag

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

## Summary by CodeRabbit

- **New Features**
	- Introduced the ability to load environment variables from a specified file.
	- Added support for prioritizing OS environment variables over those from the file.
- **Bug Fixes**
	- Adjusted function signatures to return additional information and handle new parameters.
- **Tests**
	- Added new tests to validate the behavior of environment variable file handling and priority.
- **Chores**
	- Updated `.gitignore` to include `.env.test` files.

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @cv65kr :wave: 
Thank you for the PR :heart: 

I think, that you don't need to change `expand` methods. We have the similar flag for the RR core: https://github.com/roadrunner-server/roadrunner/blob/master/internal/cli/root.go#L92

In my opinion, we only need to reserve the top-level word - `envfile` and on the very first line of the configuration, after `p.viper.ReadInConfig` (we don't need to support overrides for this option, because for the override you have to use CLI, and if you use CLI - user might use `--dotenv=path` command) parse it (to get the filepath) and use the `Load` method to populate the process envs automatically. All these envs then would be inherited automatically.

**Comment by cv65kr** [comment]
@rustatian thanks for the feedback. I tried to make a behaviour known from popular php frameworks. So there you can use .env file and override it by container environment variable. It's very helpful, because your .env file can contains sandbox api keys by default, and for production you can override it by secrets from container. 

Will update PR soon

**Comment by cv65kr** [comment]
@rustatian updated

**Review by rustatian — APPROVED** [review]
LGTM, thanks @cv65kr :+1:

**Pull request merged**
